#!/usr/bin/env python3
# SPIKE oracle for tools/gen_panel.py (D-013): layout.json -> res/OilDrumKit.svg + src/Layout.hpp.
import argparse, hashlib, json, os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
HERE = os.path.dirname(os.path.abspath(__file__))
FONT_SHA = "7da195a74c55bef988d0d48f9508bd5d849425c1770dba5d7bfc6ce9ed848954"
def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--out-dir", default=os.path.dirname(HERE)); a = ap.parse_args()
    fp = os.path.join(HERE, "fonts", "DejaVuSans.ttf")
    assert hashlib.sha256(open(fp, "rb").read()).hexdigest() == FONT_SHA, "font hash mismatch"
    f = TTFont(fp); gs = f.getGlyphSet(); cmap = f.getBestCmap(); upm = f["head"].unitsPerEm
    def text(s, cx, baseline, size):
        sc = size / upm; w = sum(gs[cmap[ord(ch)]].width for ch in s) * sc; x0 = cx - w / 2; pen = SVGPathPen(gs, lambda v: f"{v:.3f}"); adv = 0
        for ch in s:
            g = cmap[ord(ch)]; gs[g].draw(TransformPen(pen, (sc, 0, 0, -sc, x0 + adv * sc, baseline))); adv += gs[g].width
        return f'<path d="{pen.getCommands()}" fill="#e8e8e8"/>'
    lay = json.load(open(os.path.join(HERE, "layout.json"), encoding="utf-8"))
    W = lay["hp"] * 5.08; H = 128.5
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W:.2f}mm" height="{H}mm" viewBox="0 0 {W:.2f} {H}">',
           f'<rect x="0" y="0" width="{W:.2f}" height="{H}" fill="#2b2b2e"/>',
           text(lay["title"], W / 2, 9.0, 4.2), text(lay["brand"], W / 2, 125.0, 2.4)]
    for c in lay["components"]:
        if c["kind"] == "output": out.append(f'<rect x="{c["x"]-6:.2f}" y="{c["y"]-9.5:.2f}" width="12" height="15" rx="1.5" fill="#d8d8d8"/>')
    for c in lay["components"]:
        if c.get("label"):
            dy = 7.2 if c["widget"] in ("RoundBlackKnob", "CKSSThree") else 5.6
            out.append(text(c["label"], c["x"], c["y"] - dy, 2.6))
    out.append("</svg>")
    os.makedirs(os.path.join(a.out_dir, "res"), exist_ok=True); os.makedirs(os.path.join(a.out_dir, "src"), exist_ok=True)
    open(os.path.join(a.out_dir, "res", "OilDrumKit.svg"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    h = ["// GENERATED by tools/gen_panel.py from tools/layout.json -- do not edit.", "#pragma once", "namespace odk { namespace layout {",
         f"constexpr int kPanelHp = {lay['hp']};", "struct Pos { float x, y; };   // component centre, mm from top-left"]
    for c in lay["components"]: h.append(f"constexpr Pos {c['id']} = {{ {c['x']:.2f}f, {c['y']:.2f}f }};")
    h.append("} }"); open(os.path.join(a.out_dir, "src", "Layout.hpp"), "w", encoding="utf-8", newline="\n").write("\n".join(h) + "\n")
main()
