// GENERATED by tools/gen_panel.py from tools/layout.json -- do not edit.
#pragma once
namespace odk { namespace layout {
constexpr int kPanelHp = 20;
struct Pos { float x, y; };   // component centre, mm from top-left
constexpr Pos DAMP = { 14.00f, 24.00f };
constexpr Pos STRIKE = { 38.00f, 24.00f };
constexpr Pos ROOM = { 62.00f, 24.00f };
constexpr Pos TUNE = { 87.60f, 24.00f };
constexpr Pos DAMP_CV = { 14.00f, 37.00f };
constexpr Pos STRIKE_CV = { 38.00f, 37.00f };
constexpr Pos ROOM_CV = { 62.00f, 37.00f };
constexpr Pos VOCT = { 87.60f, 37.00f };
constexpr Pos HAMMER = { 30.00f, 50.00f };
constexpr Pos LIMITER = { 72.00f, 50.00f };
constexpr Pos TRIG_0 = { 12.00f, 66.00f };
constexpr Pos TRIG_1 = { 31.40f, 66.00f };
constexpr Pos TRIG_2 = { 50.80f, 66.00f };
constexpr Pos TRIG_3 = { 70.20f, 66.00f };
constexpr Pos TRIG_4 = { 89.60f, 66.00f };
constexpr Pos TRIG_5 = { 12.00f, 81.00f };
constexpr Pos TRIG_6 = { 31.40f, 81.00f };
constexpr Pos TRIG_7 = { 50.80f, 81.00f };
constexpr Pos TRIG_8 = { 70.20f, 81.00f };
constexpr Pos TRIG_9 = { 89.60f, 81.00f };
constexpr Pos TRIG_10 = { 12.00f, 96.00f };
constexpr Pos TRIG_11 = { 31.40f, 96.00f };
constexpr Pos TRIG_12 = { 50.80f, 96.00f };
constexpr Pos TRIG_13 = { 70.20f, 96.00f };
constexpr Pos TRIG_14 = { 89.60f, 96.00f };
constexpr Pos LEFT = { 70.20f, 111.00f };
constexpr Pos RIGHT = { 89.60f, 111.00f };
} }
